[package]
name = "betting_contract"
version = "0.1.0"
edition = "2018"

[dependencies]
anchor-lang = "0.30.0"
solana-program = "1.17.25"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []